#!/usr/bin/env bash

# Define desktops
bspc monitor -d "1.Web" "2.Chat" "3.Music" "4.Code" "5.Terminal" "6.Notes" "7.Games" "8.Misc" "9.Free"

bspc rule -a '*:*:Picture-in-Picture' state=floating
bspc rule -a 'qimgv' state=floating
bspc rule -a 'file-roller' state=floating

# Config
## Main
bspc config border_width            2
bspc config window_gap             8
bspc config split_ratio            0.52
bspc config borderless_monocle     true
bspc config gapless_monocle        true
bspc config focus_follows_pointer   false
bspc config pointer_follows_monitor true
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_side

## Color
### Placeholder colors
bspc config normal_border_color   "#000000" # #003f5c
bspc config active_border_color   "#000000" # #003f5c
bspc config focused_border_color  "#FFFFFF" # #ff6361
bspc config presel_feedback_color "#000000" # #ffd380

## Padding
bspc config top_padding            6
bspc config left_padding           6
bspc config right_padding          6
bspc config bottom_padding         6

# Start program
pkill -f rotate-wallpaper.sh
~/.local/bin/rotate-wallpaper.sh &

pkill -f battery-notify.sh
~/.local/bin/battery-notify.sh &

systemctl --user restart picom

pkill -f udiskie
udiskie -t &