{
  pkgs,
  iwmenu-package,
  zen-browser-package,
  prismlauncher,
  ...
}:
{
  home.packages = with pkgs; [
    dconf
    pywal16
    brightnessctl
    imagemagick
    file-roller
    direnv
    ollama-cuda
    # aichat
    fastfetch
    translate-shell
    shared-mime-info
    desktop-file-utils
    ffmpeg-full
    # walk
    libsForQt5.xp-pen-deco-01-v2-driver
    obsidian
    nautilus
    spotify
    # renterd
    fluent-reader
    libreoffice-qt6-fresh
    file-roller
    chromium
    vlc
    nekoray
    hiddify-app
    qimgv
    qbittorrent
    flameshot
    peek
    zathura
    # zen-browser-package
    prismlauncher
    filezilla
    nerd-fonts.jetbrains-mono
    monocraft
    noto-fonts
    noto-fonts-cjk-sans
    noto-fonts-emoji
    liberation_ttf
    dejavu_fonts
    inter
    corefonts
    vistafonts
    telegram-desktop
    vesktop
    iwmenu-package
    rofi-kaomoji
  ];
}
